### ISSUE TITLE
test

### ISSUE THREAD

**Issue by vecent-don** [octocat/Hello-World#2243]
GTK= 2.4.9, Linux 2.6.8.1, I200410050800, KDE 3.3.0 I'm not sure if this is the right component for this, and I'm just about to head home. Just found this in my log, and it didn't seem to have a noticeable side effects. java.lang.NullPointerException at org.eclipse.ui.internal.console.IOConsolePartitioner.getRegion(IOConsolePartitioner.java:288) at org.eclipse.ui.internal.console.IOConsoleViewer.paintControl(IOConsoleViewer.java:203) at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:82) at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:82) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:977) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1001) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:986) at org.eclipse.swt.widgets.Control.gtk_expose_event(Control.java:1801) at org.eclipse.swt.widgets.Composite.gtk_expose_event(Composite.java:421) at org.eclipse.swt.widgets.Canvas.gtk_expose_event(Canvas.java:106) at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1308) at org.eclipse.swt.widgets.Display.windowProc(Display.java:3169) at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(Native Method) at org.eclipse.swt.widgets.Display.eventProc(Display.java:902) at org.eclipse.swt.internal.gtk.OS.gtk_main_iteration(Native Method) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:2361) at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:1443) at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:1414) at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:271) at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:144) at org.eclipse.ui.internal.ide.IDEApplication.run(IDEApplication.java:102) at org.eclipse.core.internal.runtime.PlatformActivator$1.run(PlatformActivator.java:335) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:273) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:129) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:85) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:58) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:60) at java.lang.reflect.Method.invoke(Method.java:391) at org.eclipse.core.launcher.Main.basicRun(Main.java:185) at org.eclipse.core.launcher.Main.run(Main.java:684) at org.eclipse.core.launcher.Main.main(Main.java:668

**Comment by aldairandre** [comment]
Testing my bot
